### ISSUE TITLE
Compilation error on CentOS Linux 7

### ISSUE THREAD

**Issue by ekelley903** [LadnerLab/Library-Design#7]
When using the command `make optimized` I receive the following error: "make: *** No rule to make target `oligo_ecoding', needed by `optimized'.  Stop."

**Comment by ekelley903** [comment]
This actually just looks like a documentation problem in the README. The directions [here](https://ladnerlab.github.io/Library-Design/oligo_encoding/) are correct and result in a binary called 'main'.

**Comment by jtladner** [comment]
Solved by poster.
